PatGam/Projeto_Lab_Web_Grupo3

- Controllers/FuncionariosController.cs
- Models/FuncionariosViewModel.cs
Paginação e pesquisa adicionada ao controlador Funcionários;
FuncionariosViewModel criado
> Paginação e pesquisa adicionada ao controlador Funcionários;

- Controllers/ClientesController.cs
- Controllers/HomeController.cs
- Models/ListaClientesViewModel.cs
- Views/Clientes/Create.cshtml
- Views/Clientes/Delete.cshtml
- Views/Clientes/Edit.cshtml
- Views/Clientes/Index.cshtml
Criação das Views da CRUD dos Clientes;
> Criação de CRUD da Tabela de Clientes;

- Controllers/FuncionariosController.cs
- Views/Funcionarios/EliminarInserir.cshtml
- Views/Funcionarios/Inexistente.cshtml
- Views/Funcionarios/Sucesso.cshtml
Mensagens de sucesso e inexistente;
> Funcionarios controlador

- Views/Funcionarios/Create.cshtml
- Views/Pacotes/EliminarInserir.cshtml
- Views/Pacotes/Inexistente.cshtml
- Views/Pacotes/Sucesso.cshtml
- Views/Servicos/Create.cshtml
- Views/Servicos/Delete.cshtml
- Views/Servicos/Details.cshtml
- Views/Servicos/Edit.cshtml
- Views/Servicos/EliminarInserir.cshtml
- Views/Servicos/Inexistente.cshtml
- Views/Servicos/Sucesso.cshtml
- Views/ServicosPacotes/Create.cshtml
- Views/ServicosPacotes/Delete.cshtml
- Views/ServicosPacotes/Details.cshtml
- Views/ServicosPacotes/Edit.cshtml
Pacotes
Funcionarios - Criar
ServicosPacotes
> Edição Views Serviços

- Controllers/Tipos_SevicosController.cs
- Models/TiposServicosViewModel.cs
- Views/Tipos_Sevicos/EliminarInserir.cshtml
- Views/Tipos_Sevicos/Index.cshtml
- Views/Tipos_Sevicos/Inexistente.cshtml
- Views/Tipos_Sevicos/Sucesso.cshtml
Atulaziação das Views da Tabela de TiposServicos.
> Paginação e Pesquisa da tabela de TIposServicos;

- Data/SeedData.cs
> Adição dados SeedData - TipoClientes, TipoServiços

- Data/SeedData.cs
- Models/RegistoFuncionariosViewModel.cs
Mudança de email do utilizador admin;
> Correção do erro na função GaranteFuncionarios;

- Data/SeedData.cs
- Startup.cs
Mudança de email do utilizador utilizador;
> Mudança de email do utilizador cliente;

- Views/Shared/_LayoutAdmin.cshtml
- Views/Utilizadores/Details.cshtml
Botão para mudar password adicionado
> Botões Home a funcionar corretamente e Botão Password no sítio

- Controllers/UtilizadoresController.cs
- Models/Utilizadores.cs
- Views/Shared/_LayoutAdmin.cshtml
- Views/Utilizadores/CreateClientes.cshtml
- Views/Utilizadores/CreateFuncionarios.cshtml
- Views/Utilizadores/SucessoClientes.cshtml
- Views/Utilizadores/SucessoFuncionarios.cshtml
Edição da View de Sucesso para Clientes e Funcionarios;
Reparação do erro de Criar Clientes e Funcionários;
> Reparação de Erros do Controller Utilizadores

- Controllers/ContratosController.cs
- Views/Contratos/Create.cshtml
- Views/Contratos/Create2.cshtml
- Views/Contratos/Create3.cshtml
- Views/Contratos/Create4.cshtml
- Views/Contratos/Delete.cshtml
- Views/Contratos/Details.cshtml
- Views/Contratos/Index.cshtml
- Views/Contratos/Sucesso.cshtml
- Views/Pacotes/Delete.cshtml
- Views/Shared/_LayoutAdmin.cshtml
Retoques nas vistas de criar dos contratos
> Vista arquivar dos contratos completa;

- Views/Utilizadores/Details.cshtml
- Views/Utilizadores/EditClientes.cshtml
- Views/Utilizadores/SucessoClientes.cshtml
- wwwroot/TemplMain/assets/css/style.css
Correcção Vistas Detalhes, Edit e Sucesso para o Cliente
> Correção Header P.Data

- Controllers/UtilizadoresController.cs
- Views/Utilizadores/DeleteClientes.cshtml
- Views/Utilizadores/DeleteFuncionarios.cshtml
- Views/Utilizadores/IndexClientes.cshtml
Aparecimento de botão associar contrato só para operadores;
Criação da funcionalidade arquivar Clientes e Funcionarios;
> Controller Utilizadores

- Controllers/UtilizadoresController.cs
- Views/Utilizadores/CreateAdministrador.cshtml
- Views/Utilizadores/IndexAdministradores.cshtml
Função de procura exclusiva de Administradores;
Edição da procura de Funcionários para devolver só Funcionários com role de Operador;
Função de criação de Administradores;
Edição de criação de Funcionários só para criar operadores;
> Funcionários 

- Views/Shared/_LayoutAdmin.cshtml
Edição do menu de administrador:
Adição da consulta de Administradores;
Adição da criação de Administradores.
> Menu de Administrador 

- Views/Shared/_LayoutAdmin.cshtml
Edição do menu de Administrador:
Adição de Gerir Administradores,
Modificação de consulta de Clientes e Funcionários com localização da pagina de consulta de Nif e Distritos.
> Menu de Administrador

- Views/Contratos/Index.cshtml
- Views/Shared/_LayoutPData.cshtml
- Views/Utilizadores/Details.cshtml
- wwwroot/TemplMain/assets/css/style.css
Adicionados estilos CSS (tables)
Corrigida area dos clientes
> Correção ligações

- Views/Pacotes/Index.cshtml
- Views/Promocoes/Index.cshtml
- Views/Shared/_LayoutAdmin.cshtml
- wwwroot/js/PacotesList.js
- wwwroot/js/PromocoesList.js
Mudança da linguagem da tabela para português - Pacotes;
Mudança da linguagem da tabela para português - Promoções.
> Mudança da linguagem das tabelas

- Views/Shared/_LayoutAdmin.cshtml
Reparação de erros no layout Admin
> Reparação de erros

- Controllers/ContratosController.cs
- Models/NovoContratoViewModel.cs
- Views/Contratos/Create2.cshtml
- Views/Contratos/Create3.cshtml
- Views/Contratos/Create4.cshtml
Adicionada opção de 1/2 anos na fidelização
> Adicionado Distrito ao Create dos Contratos;

- Views/Home/TVBase.cshtml
- Views/Promocoes/VistaCliente.cshtml
- Views/Shared/_LayoutIndex.cshtml
- Views/Shared/_LayoutMain.cshtml
- Views/Shared/_LayoutPData.cshtml
- wwwroot/TemplMain/assets/css/style.css
- wwwroot/admin/css/style.css
Correcção cores e displays
Novas boxes (Promoçoes)(Por concluir)
> Ajuste de tamanhos

- Controllers/ContratosController.cs
- Data/SeedDataContratos.cs
- Startup.cs
- Views/Contratos/CriarContratoPasso2.cshtml
- Views/Contratos/CriarContratoPasso2Validacao.cshtml
- Views/Contratos/CriarContratoPasso3.cshtml
- Views/Contratos/CriarContratoPasso3Validacao.cshtml
- Views/Contratos/CriarContratoPasso4.cshtml
- Views/Contratos/CriarContratoPasso4Validacao.cshtml
Adicionada introdução de DistritosPromocoes e DistritosPacotes;
Listas de Pacotes e Promoções nos Contratos só mostram para o distrito do cliente
> Correção dos botões Cancelar dos Contratos;

- Views/Reclamacoes/Delete.cshtml
- Views/Reclamacoes/ViewCliente.cshtml
- Views/Utilizadores/Details.cshtml
- wwwroot/TemplMain/assets/css/style.css
> Correcção fotters e tabelas em dados pessoais e reclamações 
